"""Move the data volume onto the naming scheme in ``goalmisgen/volume.py``.

    uv run python scripts/migrate_volume.py --data /workspace/data            # plan
    uv run python scripts/migrate_volume.py --data /workspace/data --apply    # copy
    uv run python scripts/migrate_volume.py --data /workspace/data --verify   # checksum
    uv run python scripts/migrate_volume.py --data /workspace/data --retire   # set aside

Four stages, run in that order, each refusing to start until the previous one
has finished. Planning is the default and touches nothing.

**Nothing is ever deleted.** ``--retire`` moves the old paths under
``retired/``, preserving their relative layout, and the final ``rm -rf`` is left
to a human who has looked at what is in there. A rename that loses 150M steps of
training to a glob is not a recoverable mistake and this script does not put
itself in a position to make one.

The new name of a run is computed from the configuration it *saved*, never from
the directory it is currently in. An arm's offset is the difference between its
own ``objective_values`` and its base agent's, and its length is its own
``total_timesteps``. So the migration is self-checking: where the old name and
the saved configuration disagree, this reports the disagreement instead of
carrying a wrong name across to a tidier layout. The one thing that cannot be
derived is which base agent an arm belongs to — that is what ``ARM_PARENTS``
below is for, and it is deliberately a short explicit table rather than a rule.

Anything the plan does not recognise is listed as unaccounted rather than
skipped quietly, on the same principle as ``manifest.py``: an unexplained 2 GB
of checkpoints is exactly what this is meant to surface.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from goalmisgen.volume import arm_dirname, composition_arm_dirname, dataset_dirname  # noqa: E402

# Base agents, by the directory they are in today. The tag is what they become
# under ``runs/``. Seeds are written out rather than read from ``cfg.json``
# because the configuration records the *sampler* seed, which is not the number
# these runs have been called by throughout the writeups.
AGENTS: dict[str, str] = {
    "runs/maze11": "maze11.s1234",
    "runs/clean11fv": "clean11fv.s1234",
    "runs/clean11": "clean11.s1234",
    "runs/novalue11": "novalue11.s1234",
    "runs/novalue11_seed5678": "novalue11.s5678",
    "runs/smoke5b": "smoke5b",
    "threeobj/runs/base": "threeobj.even.s1234",
    "threeobj_v2/runs/base": "threeobj.uneven.s1234",
}

# Which base agent the arms in each old campaign directory were fine-tuned from.
# This is the part that cannot be derived: an arm's checkpoint does not record
# what it started from. ``threeobj2`` folding into ``threeobj.even`` is the
# point of the exercise — it was never a separate experiment, it is the same
# grid at wider offsets and longer arms, and the old name said neither.
ARM_PARENTS: dict[str, str] = {
    "valueaxis/runs": "novalue11.s1234",
    "valueaxis_s5678/runs": "novalue11.s5678",
    "threeobj/runs": "threeobj.even.s1234",
    "threeobj2/runs": "threeobj.even.s1234",
    "threeobj_v2/runs": "threeobj.uneven.s1234",
}

# Left where they are. The archived runs predate the 2026-08-04 fix and do not
# load against current code, so renaming them would imply they are usable.
LEAVE_ALONE = ("runs/archive", "archive", "retired")


@dataclass
class Move:
    source: Path
    destination: Path
    why: str


@dataclass
class Plan:
    moves: list[Move] = field(default_factory=list)
    unaccounted: list[tuple[Path, str]] = field(default_factory=list)
    # Datasets that are byte-identical to one already being moved. They are the
    # point of a shared library rather than a problem with it: the same values at
    # the same size generated by the same code really is one dataset, however
    # many campaigns asked for a copy.
    duplicates: list[tuple[Path, Path]] = field(default_factory=list)

    def collisions(self) -> dict[Path, list[Path]]:
        by_destination: dict[Path, list[Path]] = {}
        for move in self.moves:
            by_destination.setdefault(move.destination, []).append(move.source)
        return {d: s for d, s in by_destination.items() if len(s) > 1}


def left_alone(relative: Path) -> bool:
    return any(str(relative) == prefix or str(relative).startswith(prefix + "/") for prefix in LEAVE_ALONE)


def run_config(run: Path) -> dict:
    """A run's saved configuration: values, objective count, steps, dataset.

    ``013`` writes the reset checkpoint's config under ``init``; a base training
    run has one inside each checkpoint. Reading the newest checkpoint's config
    for a base run and ``init`` for an arm means both answer the same questions.
    """
    for candidate in sorted(run.glob("init/cfg.json")) + sorted(run.glob("local-files/cp_*/cfg.json"), reverse=True):
        try:
            payload = json.loads(candidate.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        config = payload.get("cfg", payload)
        env = config.get("train_env", {})
        return {
            "values": tuple(env.get("objective_values") or ()),
            "objectives": env.get("n_objectives"),
            "steps": config.get("total_timesteps"),
            "levels": env.get("level_dataset") or "",
        }
    return {}


# Old arm names, and which objective each sweep moved. Needed only for the null
# arms; every other arm says which objective it moved by having moved it.
_OLD_SWEEP = re.compile(r"^(?:(?P<colour>[vc])\d{3}|o(?P<objective>\d)_\d{3})$")


def sweep_objective(old_name: str) -> int | None:
    """Which objective an old arm directory belonged to, or ``None``.

    ``v`` swept colour 1 and ``c`` swept colour 0; the three-objective grids say
    it outright.
    """
    match = _OLD_SWEEP.fullmatch(old_name)
    if match is None:
        return None
    if match.group("colour"):
        return 1 if match.group("colour") == "v" else 0
    return int(match.group("objective"))


def arm_name(
    base_values: tuple[float, ...],
    arm_values: tuple[float, ...],
    steps: int,
    null_objective: int | None = None,
) -> str:
    """What one arm is called, from what it was trained on rather than its old name.

    An arm that moved exactly one objective is that objective's sweep at the
    offset it moved by. An arm that moved several is a composition arm, held out
    of every fit, and is named for the values it carries because it has no
    single offset to be named for.

    The null arms are the exception, and the only place this has to fall back on
    the old name. Each sweep has one, fine-tuned onto the value the agent already
    had, and their configurations are identical to the base and to each other --
    so nothing in what they were trained on says which sweep they measure the
    drift of. That information exists only in what they were called. Both are
    real and distinct runs, so collapsing them would silently throw one away.
    """
    if len(base_values) != len(arm_values):
        raise ValueError(f"arm has {len(arm_values)} objectives against the base's {len(base_values)}")
    moved = [i for i, (b, a) in enumerate(zip(base_values, arm_values)) if abs(a - b) > 1e-9]
    if len(moved) == 1:
        index = moved[0]
        return arm_dirname(f"o{index}", arm_values[index] - base_values[index], steps)
    if not moved:
        if null_objective is None:
            raise ValueError(
                "this arm was trained at the base values, so it is a null arm, but its old name "
                "does not say which sweep it belongs to and its configuration cannot"
            )
        return arm_dirname(f"o{null_objective}", 0.0, steps)
    return composition_arm_dirname(arm_values, steps)


def plan_runs(root: Path) -> Plan:
    plan = Plan()
    base_values: dict[str, tuple[float, ...]] = {}

    # Base agents first, since an arm's offset is measured against its base's values.
    for old, tag in AGENTS.items():
        run = root / old
        if not run.is_dir():
            plan.unaccounted.append((Path(old), "named in AGENTS but not on the volume"))
            continue
        config = run_config(run)
        if not config.get("values"):
            plan.unaccounted.append((Path(old), "no readable cfg.json, so its values are unknown"))
            continue
        base_values[tag] = config["values"]
        plan.moves.append(Move(run, root / "runs" / tag, f"base agent, values {config['values']}"))

    for parent, tag in ARM_PARENTS.items():
        directory = root / parent
        if not directory.is_dir():
            plan.unaccounted.append((Path(parent), "named in ARM_PARENTS but not on the volume"))
            continue
        if tag not in base_values:
            plan.unaccounted.append((Path(parent), f"arms of {tag}, whose base agent was not resolved"))
            continue
        for run in sorted(directory.iterdir()):
            if not (run / "local-files").is_dir() or run.name == "base":
                continue
            config = run_config(run)
            if not config.get("values") or not config.get("steps"):
                plan.unaccounted.append((run.relative_to(root), "no readable cfg.json"))
                continue
            try:
                name = arm_name(base_values[tag], config["values"], config["steps"], sweep_objective(run.name))
            except ValueError as error:
                plan.unaccounted.append((run.relative_to(root), str(error)))
                continue
            plan.moves.append(Move(run, root / "runs" / tag / "arms" / name, f"arm of {tag}, values {config['values']}"))
    return plan


def plan_datasets(root: Path) -> Plan:
    """Every level dataset into one library keyed by values and level count.

    Datasets that differ only in what the objectives pay share their layouts
    byte for byte, so one copy of each key serves every seed and every campaign.
    Randomised-value datasets have no fixed tuple to be keyed by and keep their
    own names.
    """
    plan = Plan()
    for meta in sorted(root.rglob("meta.json")):
        directory = meta.parent
        relative = directory.relative_to(root)
        if left_alone(relative):
            continue
        try:
            payload = json.loads(meta.read_text())
        except (OSError, json.JSONDecodeError):
            plan.unaccounted.append((relative, "meta.json does not parse"))
            continue
        count = payload.get("n_levels")
        values = _dataset_values(directory)
        if values is None:
            plan.moves.append(Move(directory, root / "levels" / "randomised" / directory.name, "values vary per level"))
            continue
        if not count:
            plan.unaccounted.append((relative, "meta.json records no level count"))
            continue
        try:
            name = dataset_dirname(values, count)
        except ValueError as error:
            plan.unaccounted.append((relative, str(error)))
            continue
        plan.moves.append(Move(directory, root / "levels" / "values" / name, f"{count:,} levels at {values}"))
    return _resolve_duplicate_datasets(plan)


def _resolve_duplicate_datasets(plan: Plan) -> Plan:
    """Collapse datasets that are the same bytes, and refuse the ones that are not.

    Several campaigns generated their own copy of, say, 500k levels at (1.0,
    0.5), and one copy should serve all of them. But "same values, same count"
    is not by itself enough to make two datasets interchangeable: the train,
    validation and test membership is stored *in* the dataset, precisely so that
    changing a holdout size cannot silently move levels between splits, and two
    datasets built with different holdouts would share a key while disagreeing
    about which levels an agent may train on.

    So sameness is decided by comparing the files rather than by trusting the
    key. Identical copies collapse; anything else stops the migration, because
    the alternative is an agent evaluated on levels it trained on.
    """
    kept: dict[Path, Move] = {}
    resolved = Plan(unaccounted=list(plan.unaccounted))
    for move in plan.moves:
        first = kept.get(move.destination)
        if first is None:
            kept[move.destination] = move
            resolved.moves.append(move)
            continue
        if tree_checksums(move.source) == tree_checksums(first.source):
            resolved.duplicates.append((move.source, first.source))
        else:
            resolved.unaccounted.append(
                (
                    move.source,
                    f"wants {move.destination.name}, which {first.source.name} already holds with "
                    "different contents — same values and size, different levels or splits",
                )
            )
    return resolved


def _dataset_values(directory: Path) -> tuple[float, ...] | None:
    """The objective values every level in a dataset carries, or ``None`` if they vary."""
    import numpy as np

    try:
        stored = np.load(directory / "values.npy")
    except (OSError, ValueError):
        return None
    if stored.ndim != 2 or len(stored) == 0:
        return None
    first = stored[0]
    if not np.allclose(stored, first):
        return None
    return tuple(round(float(v), 2) for v in first)


def write_base_json(agent: Path, config: dict) -> Path | None:
    """Record which checkpoint of an agent everything downstream should resolve.

    The newest saved checkpoint, which is the right one for both the runs that
    finished where they meant to and ``threeobj.even``, whose last 10M steps
    were trained and discarded because the inherited ``eval_at_steps`` jumped
    past the final update. That is the whole reason this file exists rather than
    a hardcoded ``cp_140206080`` in a shell script: the rule is stable even where
    the number is surprising.
    """
    checkpoints = sorted((agent / "local-files").glob("cp_*"))
    if not checkpoints:
        return None
    payload = {
        "checkpoint": str(checkpoints[-1].relative_to(agent)),
        "values": list(config.get("values") or ()),
        "objectives": config.get("objectives"),
        "steps": config.get("steps"),
        "checkpoints_saved": len(checkpoints),
    }
    destination = agent / "BASE.json"
    destination.write_text(json.dumps(payload, indent=2) + "\n")
    return destination


def checksum(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def is_within(path: Path, directory: Path) -> bool:
    return path == directory or directory in path.parents


def tree_checksums(directory: Path, exclude: tuple[Path, ...] = ()) -> dict[str, str]:
    """Every file under ``directory``, except what lives in a nested destination.

    Arms are copied *inside* the agent they were fine-tuned from, so the new
    ``runs/novalue11.s1234`` holds both the base agent's own checkpoints and
    every arm's. Checksumming it whole would compare the base agent's old
    directory against the base agent plus sixty arms and call it corrupted.
    """
    return {
        str(f.relative_to(directory)): checksum(f)
        for f in sorted(directory.rglob("*"))
        if f.is_file() and not any(is_within(f, e) for e in exclude)
    }


def report(plan: Plan, title: str, root: Path) -> None:
    print(f"\n=== {title} ===")
    for move in plan.moves:
        print(f"  {str(move.source.relative_to(root)):<34} -> {move.destination.relative_to(root)}")
        print(f"  {'':<34}    {move.why}")
    for source, first in plan.duplicates:
        print(f"  DUPLICATE    {source.relative_to(root)} is byte-identical to {first.relative_to(root)}")
    for path, reason in plan.unaccounted:
        print(f"  UNACCOUNTED  {path}: {reason}")
    collisions = plan.collisions()
    for destination, sources in collisions.items():
        print(f"  COLLISION  {destination.name} <- {', '.join(s.name for s in sources)}")
    print(
        f"  {len(plan.moves)} moves, {len(plan.duplicates)} duplicates, "
        f"{len(plan.unaccounted)} unaccounted, {len(collisions)} collisions"
    )


def apply(plan: Plan, record: Path) -> int:
    """Copy every planned move, leaving the source untouched.

    Shallowest destination first, so an agent's own directory is created before
    the arms that nest inside it. ``copytree`` refuses an existing destination,
    so the reverse order would fail on the agent rather than on the arm, and the
    reason would be several lines away from the cause.
    """
    done = []
    for move in sorted(plan.moves, key=lambda m: len(m.destination.parts)):
        if move.destination.exists():
            print(f"  present  {move.destination}")
            done.append(move)
            continue
        print(f"  copying  {move.source} -> {move.destination}")
        move.destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copytree(move.source, move.destination)
        done.append(move)
    record.write_text(
        json.dumps(
            {
                "moves": [{"from": str(m.source), "to": str(m.destination), "why": m.why} for m in done],
                "duplicates": [{"from": str(s), "same_as": str(f)} for s, f in plan.duplicates],
            },
            indent=2,
        )
    )
    print(f"\nwrote {record} — the record of what moved where, and how to undo it")
    return len(done)


def recorded_moves(record: Path) -> list[dict]:
    return json.loads(record.read_text())["moves"]


def verify(record: Path) -> int:
    """Every file at the new path must be byte-identical to the one at the old.

    A checksum of the whole tree rather than a spot check, because the failure
    being guarded against is a partial copy, and a partial copy of a checkpoint
    directory looks entirely normal until something loads it.
    """
    moves = recorded_moves(record)
    everywhere = [Path(entry["to"]) for entry in moves]
    failures = 0
    for entry in moves:
        source, destination = Path(entry["from"]), Path(entry["to"])
        nested = tuple(d for d in everywhere if d != destination and is_within(d, destination))
        before, after = tree_checksums(source), tree_checksums(destination, exclude=nested)
        if before == after:
            print(f"  ok       {destination.name}  ({len(before)} files)")
            continue
        failures += 1
        missing = sorted(set(before) - set(after))
        extra = sorted(set(after) - set(before))
        changed = sorted(f for f in set(before) & set(after) if before[f] != after[f])
        print(f"  FAILED   {destination}")
        for label, items in (("missing", missing), ("extra", extra), ("changed", changed)):
            if items:
                print(f"             {label}: {', '.join(items[:4])}{' ...' if len(items) > 4 else ''}")
    print(f"\n{len(moves) - failures}/{len(moves)} verified")
    return failures


def finalise(root: Path) -> None:
    """Write each agent's ``BASE.json`` once the copies have been verified.

    After verification rather than during the copy, because verification
    compares the new tree against the old one file for file and a ``BASE.json``
    that exists only on the new side would read as a corrupted copy.
    """
    for tag in sorted(set(AGENTS.values())):
        agent = root / "runs" / tag
        if not agent.is_dir():
            continue
        written = write_base_json(agent, run_config(agent))
        print(f"  {'wrote   ' if written else 'no cp_*, skipped '} {tag}/BASE.json")


def retire(record: Path, root: Path) -> None:
    """Move the old paths aside, redundant copies included. Nothing is deleted."""
    payload = json.loads(record.read_text())
    retiring = [entry["from"] for entry in payload["moves"]]
    retiring += [entry["from"] for entry in payload.get("duplicates", [])]
    for old in retiring:
        source = Path(old)
        if not source.exists():
            continue
        destination = root / "retired" / source.relative_to(root)
        destination.parent.mkdir(parents=True, exist_ok=True)
        print(f"  retiring {source.relative_to(root)}")
        shutil.move(str(source), str(destination))
    print(f"\nOld paths are under {root / 'retired'}. Nothing has been deleted.")
    print("Delete them yourself once the analysis has run against the new layout.")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--data", type=Path, default=Path("/workspace/data"))
    parser.add_argument("--apply", action="store_true", help="Copy to the new paths, leaving the old ones.")
    parser.add_argument("--verify", action="store_true", help="Checksum every copied file against its source.")
    parser.add_argument("--retire", action="store_true", help="Move verified old paths under retired/.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    record = args.data / "MIGRATION.json"

    if args.retire:
        if not record.is_file():
            sys.exit("Nothing to retire: run --apply and --verify first.")
        if verify(record) != 0:
            sys.exit("\nVerification failed, so nothing has been retired. Fix the copies and re-verify.")
        finalise(args.data)
        retire(record, args.data)
        return

    if args.verify:
        if not record.is_file():
            sys.exit("Nothing to verify: run --apply first.")
        sys.exit(1 if verify(record) else 0)

    runs, datasets = plan_runs(args.data), plan_datasets(args.data)
    report(runs, "runs", args.data)
    report(datasets, "level datasets", args.data)

    combined = Plan(
        runs.moves + datasets.moves,
        runs.unaccounted + datasets.unaccounted,
        runs.duplicates + datasets.duplicates,
    )
    if combined.collisions():
        sys.exit("\nTwo things want the same new path. Resolve that before copying anything.")

    if not args.apply:
        print("\nThis was a plan. Re-run with --apply to copy, then --verify, then --retire.")
        return

    apply(combined, record)
    print("\nNow run --verify. Nothing is retired until it passes.")


if __name__ == "__main__":
    main()
